const diseases = [
    {
        name: "Flu (Influenza)",
        description: "Flu adalah infeksi virus yang menyerang saluran pernapasan, seringkali menyebabkan demam, batuk, dan sakit tenggorokan.",
        symptoms: ["demam", "batuk", "sakit tenggorokan", "pilek", "sakit kepala", "nyeri otot"],
        severity: "Ringan",
        emergencyTreatment: "Istirahat, minum banyak cairan, dan konsumsi obat flu yang dijual bebas.",
        treatmentMethod: "Pengobatan simtomatik, seperti obat penurun demam dan pereda nyeri.",
        specialist: "Dokter Umum",
        source: "https://www.alodokter.com/flu",
        features: ["Demam mendadak", "Batuk kering", "Sakit tenggorokan"],
        medicineInfo: "Obat antivirus seperti oseltamivir (Tamiflu) jika diperlukan.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Batuk Rejan",
        description: "Batuk Rejan adalah infeksi bakteri yang menyebabkan batuk parah dan berkepanjangan.",
        symptoms: ["batuk parah", "napas pendek", "muntah setelah batuk"],
        severity: "Serius",
        emergencyTreatment: "Segera konsultasikan ke dokter. Obat antibiotik akan diberikan.",
        treatmentMethod: "Antibiotik sesuai resep dokter dan perawatan suportif.",
        specialist: "Dokter Spesialis Anak",
        source: "https://www.klikdokter.com/penyakit/batuk-rejan",
        features: ["Batuk berulang dengan suara whoop", "Kesulitan bernapas"],
        medicineInfo: "Antibiotik seperti azitromisin atau klaritromisin.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Gastritis",
        description: "Gastritis adalah peradangan pada lapisan lambung yang dapat menyebabkan nyeri perut dan mual.",
        symptoms: ["nyeri perut", "mual", "muntah", "kembung"],
        severity: "Ringan",
        emergencyTreatment: "Hindari makanan yang dapat mengiritasi lambung. Konsultasikan dengan dokter jika gejala berlanjut.",
        treatmentMethod: "Obat antasid dan penghambat asam lambung.",
        specialist: "Dokter Spesialis Penyakit Dalam",
        source: "https://www.halodoc.com/gastritis",
        features: ["Nyeri perut bagian atas", "Kembung dan rasa penuh"],
        medicineInfo: "Antasid seperti ranitidin dan penghambat proton pump seperti omeprazol.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Diabetes Tipe 2",
        description: "Diabetes Tipe 2 adalah gangguan metabolisme yang menyebabkan kadar gula darah tinggi.",
        symptoms: ["sering haus", "sering buang air kecil", "kelelahan", "penurunan berat badan"],
        severity: "Serius",
        emergencyTreatment: "Kontrol kadar gula darah dan konsultasikan dengan dokter untuk pengelolaan lebih lanjut.",
        treatmentMethod: "Obat antidiabetes oral dan insulin jika diperlukan.",
        specialist: "Dokter Spesialis Endokrinologi",
        source: "https://www.klikdokter.com/penyakit/diabetes-tipe-2",
        features: ["Sering haus dan buang air kecil", "Kelelahan berlebih"],
        medicineInfo: "Metformin adalah obat pertama yang biasa diresepkan.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Asma",
        description: "Asma adalah kondisi kronis yang menyebabkan saluran pernapasan meradang dan menyempit, sehingga sulit bernapas.",
        symptoms: ["sesak napas", "batuk", "dada terasa sesak"],
        severity: "Serius",
        emergencyTreatment: "Gunakan inhaler pengontrol atau bronkodilator. Jika tidak membaik, segera hubungi dokter.",
        treatmentMethod: "Inhaler steroid dan bronkodilator.",
        specialist: "Dokter Spesialis Paru",
        source: "https://www.alodokter.com/asthma",
        features: ["Sesak napas yang datang dan pergi", "Batuk saat malam atau pagi"],
        medicineInfo: "Inhaler seperti salbutamol dan fluticasone.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Infeksi Saluran Pernapasan Atas (ISPA)",
        description: "ISPA adalah infeksi yang mempengaruhi bagian atas saluran pernapasan, seperti hidung dan tenggorokan.",
        symptoms: ["pilek", "batuk", "sakit tenggorokan", "demam ringan"],
        severity: "Ringan",
        emergencyTreatment: "Minum banyak cairan dan istirahat. Obat bebas seperti dekongestan dapat membantu.",
        treatmentMethod: "Obat dekongestan dan analgesik.",
        specialist: "Dokter Umum",
        source: "https://www.halodoc.com/ispa",
        features: ["Pilek yang berlangsung beberapa hari", "Sakit tenggorokan ringan"],
        medicineInfo: "Obat dekongestan seperti pseudoefedrin dan analgesik seperti parasetamol.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Bronkitis",
        description: "Bronkitis adalah peradangan pada bronkus yang dapat menyebabkan batuk dan produksi lendir.",
        symptoms: ["batuk produktif", "nyeri dada", "sesak napas"],
        severity: "Ringan hingga Serius",
        emergencyTreatment: "Minum banyak cairan dan gunakan obat batuk sesuai resep.",
        treatmentMethod: "Obat batuk dan bronkodilator jika diperlukan.",
        specialist: "Dokter Spesialis Paru",
        source: "https://www.klikdokter.com/penyakit/bronkitis",
        features: ["Batuk dengan lendir", "Sesak napas"],
        medicineInfo: "Obat batuk seperti guaifenesin dan bronkodilator seperti albuterol.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Tipes (Demam Typhoid)",
        description: "Tipes adalah infeksi bakteri yang disebabkan oleh Salmonella typhi, sering ditandai dengan demam tinggi.",
        symptoms: ["demam tinggi", "nyeri perut", "mual", "muntah"],
        severity: "Serius",
        emergencyTreatment: "Segera hubungi dokter untuk pengobatan antibiotik.",
        treatmentMethod: "Antibiotik seperti kloramfenikol atau ciprofloxacin.",
        specialist: "Dokter Spesialis Penyakit Dalam",
        source: "https://www.halodoc.com/tipes",
        features: ["Demam tinggi berkepanjangan", "Nyeri perut dan ruam kulit"],
        medicineInfo: "Antibiotik sesuai resep dokter.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Hepatitis A",
        description: "Hepatitis A adalah infeksi virus yang mempengaruhi hati dan biasanya disebarkan melalui makanan atau air yang terkontaminasi.",
        symptoms: ["demam", "sakit perut", "kuning pada kulit", "mual"],
        severity: "Serius",
        emergencyTreatment: "Segera periksakan ke dokter untuk pengelolaan dan perawatan lebih lanjut.",
        treatmentMethod: "Istirahat dan konsumsi makanan yang sehat. Tidak ada obat khusus.",
        specialist: "Dokter Spesialis Penyakit Dalam",
        source: "https://www.klikdokter.com/penyakit/hepatitis-a",
        features: ["Kuning pada kulit dan mata", "Nyeri perut bagian atas"],
        medicineInfo: "Tidak ada obat spesifik. Fokus pada perawatan simptomatik.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Cacar Air",
        description: "Cacar air adalah infeksi virus yang menyebabkan ruam kulit dan gatal-gatal.",
        symptoms: ["ruam gatal", "demam", "lesi berisi cairan"],
        severity: "Ringan",
        emergencyTreatment: "Gunakan krim antihistamin dan kompres dingin untuk mengurangi gatal.",
        treatmentMethod: "Antihistamin dan obat pereda gatal.",
        specialist: "Dokter Umum",
        source: "https://www.alodokter.com/cacar-air",
        features: ["Ruam gatal yang berkembang menjadi lepuhan", "Demam ringan"],
        medicineInfo: "Obat antihistamin seperti diphenhydramine dan krim pereda gatal.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Herpes Simpleks",
        description: "Herpes Simpleks adalah infeksi virus yang menyebabkan luka dingin di mulut atau genital.",
        symptoms: ["lesi di mulut", "nyeri saat berkemih", "ruam genital"],
        severity: "Serius",
        emergencyTreatment: "Gunakan obat antivirus sesuai resep dokter.",
        treatmentMethod: "Obat antivirus seperti asiklovir.",
        specialist: "Dokter Spesialis Kulit dan Kelamin",
        source: "https://www.klikdokter.com/penyakit/herpes-simpleks",
        features: ["Luka berisi cairan yang menyakitkan", "Gatal atau nyeri pada area yang terkena"],
        medicineInfo: "Obat antivirus seperti asiklovir atau valasiklovir.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Penyakit Jantung Koroner",
        description: "Penyakit jantung koroner adalah kondisi yang disebabkan oleh penyempitan arteri jantung akibat penumpukan plak.",
        symptoms: ["nyeri dada", "sesak napas", "mual"],
        severity: "Serius",
        emergencyTreatment: "Hubungi layanan darurat segera dan ikuti instruksi dokter.",
        treatmentMethod: "Obat-obatan seperti statin dan prosedur medis seperti angioplasti.",
        specialist: "Dokter Spesialis Jantung",
        source: "https://www.alodokter.com/penyakit-jantung-koroner",
        features: ["Nyeri dada yang menjalar ke lengan atau rahang", "Sesak napas"],
        medicineInfo: "Statin seperti simvastatin dan obat pengencer darah.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Kolesterol Tinggi",
        description: "Kolesterol tinggi adalah kondisi di mana kadar kolesterol dalam darah meningkat, meningkatkan risiko penyakit jantung.",
        symptoms: ["tidak ada gejala", "pemeriksaan darah menunjukkan kadar kolesterol tinggi"],
        severity: "Ringan hingga Serius",
        emergencyTreatment: "Konsumsi obat penurun kolesterol dan lakukan perubahan gaya hidup.",
        treatmentMethod: "Obat statin dan diet rendah lemak.",
        specialist: "Dokter Spesialis Jantung atau Dokter Umum",
        source: "https://www.halodoc.com/kolesterol-tinggi",
        features: ["Peningkatan kadar kolesterol dalam darah"],
        medicineInfo: "Obat statin seperti atorvastatin atau simvastatin.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Pneumonia",
        description: "Pneumonia adalah infeksi pada paru-paru yang dapat disebabkan oleh bakteri, virus, atau jamur.",
        symptoms: ["batuk", "demam", "sesak napas", "nyeri dada"],
        severity: "Serius",
        emergencyTreatment: "Segera bawa ke rumah sakit untuk perawatan antibiotik dan oksigen.",
        treatmentMethod: "Antibiotik, perawatan suportif, dan oksigen jika diperlukan.",
        specialist: "Dokter Spesialis Paru",
        source: "https://www.alodokter.com/pneumonia",
        features: ["Batuk dengan lendir", "Sesak napas yang memburuk"],
        medicineInfo: "Antibiotik sesuai resep dokter.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Sinusitis",
        description: "Sinusitis adalah peradangan pada sinus yang menyebabkan sakit kepala, hidung tersumbat, dan nyeri wajah.",
        symptoms: ["sakit kepala", "hidung tersumbat", "nyeri wajah", "batuk"],
        severity: "Ringan hingga Serius",
        emergencyTreatment: "Gunakan dekongestan dan lakukan kompres hangat.",
        treatmentMethod: "Dekongestan dan pengobatan antibiotik jika disebabkan oleh infeksi bakteri.",
        specialist: "Dokter THT",
        source: "https://www.halodoc.com/sinusitis",
        features: ["Nyeri di sekitar dahi dan hidung", "Hidung tersumbat yang berlangsung lama"],
        medicineInfo: "Obat dekongestan seperti pseudoefedrin dan antibiotik jika diperlukan.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Diare",
        description: "Diare adalah kondisi di mana seseorang mengalami tinja yang sering dan cair, sering disertai dengan nyeri perut.",
        symptoms: ["diare", "nyeri perut", "demam", "mual"],
        severity: "Ringan hingga Serius",
        emergencyTreatment: "Minum oralit untuk mencegah dehidrasi dan hindari makanan berat.",
        treatmentMethod: "Penggantian cairan, obat antidiarrhea seperti loperamid.",
        specialist: "Dokter Spesialis Penyakit Dalam",
        source: "https://www.klikdokter.com/penyakit/diare",
        features: ["Tinja cair yang sering", "Nyeri perut"],
        medicineInfo: "Obat antidiarrhea seperti loperamid.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Rinitis Alergi",
        description: "Rinitis alergi adalah peradangan pada lapisan hidung yang disebabkan oleh alergi terhadap alergen.",
        symptoms: ["hidung tersumbat", "bersin", "gatal di hidung", "mata berair"],
        severity: "Ringan",
        emergencyTreatment: "Hindari alergen dan gunakan antihistamin.",
        treatmentMethod: "Antihistamin dan dekongestan.",
        specialist: "Dokter Spesialis Alergi",
        source: "https://www.halodoc.com/rinitis-alergi",
        features: ["Bersin yang sering", "Gatal dan berair di hidung dan mata"],
        medicineInfo: "Antihistamin seperti loratadin dan dekongestan seperti pseudoefedrin.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Gerd (Gastroesophageal Reflux Disease)",
        description: "GERD adalah kondisi di mana asam lambung mengalir kembali ke kerongkongan, menyebabkan nyeri dan ketidaknyamanan.",
        symptoms: ["nyeri dada", "heartburn", "regurgitasi asam", "sakit tenggorokan"],
        severity: "Serius",
        emergencyTreatment: "Hindari makanan yang memicu gejala dan gunakan penghambat asam.",
        treatmentMethod: "Penghambat asam lambung dan perubahan gaya hidup.",
        specialist: "Dokter Spesialis Penyakit Dalam",
        source: "https://www.klikdokter.com/penyakit/gerd",
        features: ["Nyeri dada setelah makan", "Regurgitasi asam"],
        medicineInfo: "Obat penghambat asam seperti omeprazol.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Migrain",
        description: "Migrain adalah jenis sakit kepala berat yang sering disertai dengan mual dan sensitivitas terhadap cahaya.",
        symptoms: ["sakit kepala berat", "mual", "sensitif terhadap cahaya", "pusing"],
        severity: "Serius",
        emergencyTreatment: "Gunakan obat pereda migrain dan istirahat di tempat gelap.",
        treatmentMethod: "Obat pereda migrain dan perubahan gaya hidup.",
        specialist: "Dokter Spesialis Saraf",
        source: "https://www.halodoc.com/migrain",
        features: ["Sakit kepala yang berdenyut", "Nausea dan muntah"],
        medicineInfo: "Obat migrain seperti sumatriptan.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Alergi Makanan",
        description: "Alergi makanan adalah reaksi tubuh terhadap makanan tertentu yang dapat menyebabkan berbagai gejala.",
        symptoms: ["ruam kulit", "gatal", "mual", "kesulitan bernapas"],
        severity: "Serius",
        emergencyTreatment: "Hindari makanan pemicu dan gunakan antihistamin atau epinefrin jika diperlukan.",
        treatmentMethod: "Antihistamin dan epinefrin untuk reaksi berat.",
        specialist: "Dokter Spesialis Alergi",
        source: "https://www.klikdokter.com/penyakit/alergi-makanan",
        features: ["Reaksi setelah makan makanan tertentu", "Gatal dan ruam kulit"],
        medicineInfo: "Antihistamin seperti cetirizine dan epinefrin.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Penyakit Maag",
        description: "Penyakit maag adalah peradangan pada lapisan lambung yang menyebabkan nyeri perut.",
        symptoms: ["nyeri perut", "mual", "muntah", "kembung"],
        severity: "Serius",
        emergencyTreatment: "Hindari makanan yang mengiritasi lambung dan konsultasikan dengan dokter.",
        treatmentMethod: "Obat antasid dan penghambat asam lambung.",
        specialist: "Dokter Spesialis Penyakit Dalam",
        source: "https://www.halodoc.com/penyakit-maag",
        features: ["Nyeri perut yang sering", "Mual dan muntah"],
        medicineInfo: "Obat antasid seperti ranitidin dan omeprazol.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Penyakit Paru Obstruktif Kronis (PPOK)",
        description: "PPOK adalah gangguan paru-paru kronis yang menyebabkan kesulitan bernapas.",
        symptoms: ["sesak napas", "batuk kronis", "produksi lendir"],
        severity: "Serius",
        emergencyTreatment: "Gunakan bronkodilator dan konsultasikan dengan dokter.",
        treatmentMethod: "Bronkodilator dan steroid inhalasi.",
        specialist: "Dokter Spesialis Paru",
        source: "https://www.alodokter.com/ppok",
        features: ["Sesak napas yang kronis", "Batuk dengan produksi lendir"],
        medicineInfo: "Obat bronkodilator dan steroid inhalasi.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "TBC (Tuberkulosis)",
        description: "TBC adalah infeksi bakteri yang mempengaruhi paru-paru dan dapat menyebar ke bagian tubuh lainnya.",
        symptoms: ["batuk berdarah", "demam", "penurunan berat badan", "keringat malam"],
        severity: "Serius",
        emergencyTreatment: "Konsultasikan dengan dokter untuk terapi antibiotik jangka panjang.",
        treatmentMethod: "Antibiotik selama beberapa bulan.",
        specialist: "Dokter Spesialis Paru",
        source: "https://www.halodoc.com/tbc",
        features: ["Batuk berkepanjangan dengan darah", "Penurunan berat badan"],
        medicineInfo: "Antibiotik TBC seperti isoniazid dan rifampisin.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Penyakit Celiac",
        description: "Penyakit Celiac adalah gangguan autoimun di mana tubuh bereaksi terhadap gluten, protein yang terdapat pada gandum.",
        symptoms: ["nyeri perut", "diare", "penurunan berat badan", "kelelahan"],
        severity: "Serius",
        emergencyTreatment: "Hindari gluten dan konsultasikan dengan dokter.",
        treatmentMethod: "Diet bebas gluten.",
        specialist: "Dokter Spesialis Gastroenterologi",
        source: "https://www.klikdokter.com/penyakit/celiac",
        features: ["Nyeri perut setelah makan gluten", "Diare kronis"],
        medicineInfo: "Tidak ada obat, fokus pada diet bebas gluten.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Stroke",
        description: "Stroke adalah kondisi medis darurat yang terjadi ketika pasokan darah ke bagian otak terputus.",
        symptoms: ["kelumpuhan mendadak", "kesulitan berbicara", "pusing", "sakit kepala hebat"],
        severity: "Serius",
        emergencyTreatment: "Segera hubungi layanan darurat dan cari perawatan medis segera.",
        treatmentMethod: "Perawatan darurat untuk mengembalikan aliran darah dan rehabilitasi.",
        specialist: "Dokter Spesialis Saraf",
        source: "https://www.halodoc.com/stroke",
        features: ["Kelumpuhan di satu sisi tubuh", "Kesulitan berbicara dan memahami"],
        medicineInfo: "Obat pengencer darah dan terapi untuk rehabilitasi.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Penyakit Crohn",
        description: "Penyakit Crohn adalah kondisi inflamasi kronis pada saluran pencernaan.",
        symptoms: ["nyeri perut", "diare", "penurunan berat badan", "kekurangan gizi"],
        severity: "Serius",
        emergencyTreatment: "Segera konsultasikan dengan dokter untuk pengobatan jangka panjang.",
        treatmentMethod: "Obat anti-inflamasi dan imunosupresan.",
        specialist: "Dokter Spesialis Gastroenterologi",
        source: "https://www.klikdokter.com/penyakit/crohn",
        features: ["Nyeri perut berulang", "Diare yang berlangsung lama"],
        medicineInfo: "Obat anti-inflamasi seperti mesalazine dan imunosupresan seperti azathioprine.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Penyakit Ginjal Kronis",
        description: "Penyakit ginjal kronis adalah kondisi di mana fungsi ginjal menurun secara bertahap.",
        symptoms: ["pembengkakan kaki", "kelelahan", "mual", "nafsu makan menurun"],
        severity: "Serius",
        emergencyTreatment: "Segera periksa fungsi ginjal dan ikuti pengobatan yang direkomendasikan.",
        treatmentMethod: "Pengobatan untuk memperlambat kerusakan ginjal dan dialisis jika diperlukan.",
        specialist: "Dokter Spesialis Ginjal",
        source: "https://www.halodoc.com/penyakit-ginjal-kronis",
        features: ["Pembengkakan kaki dan pergelangan kaki", "Kelelahan dan mual"],
        medicineInfo: "Obat yang memperlambat kerusakan ginjal dan pengobatan dialisis.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Rheumatoid Arthritis",
        description: "Rheumatoid arthritis adalah penyakit autoimun yang menyebabkan peradangan pada sendi.",
        symptoms: ["nyeri sendi", "pembengkakan sendi", "kekakuan", "kelelahan"],
        severity: "Serius",
        emergencyTreatment: "Gunakan obat antiinflamasi dan konsultasikan dengan dokter untuk pengelolaan jangka panjang.",
        treatmentMethod: "Obat antiinflamasi non-steroid (NSAID) dan imunosupresan.",
        specialist: "Dokter Spesialis Reumatologi",
        source: "https://www.halodoc.com/rheumatoid-arthritis",
        features: ["Nyeri dan pembengkakan pada sendi", "Kekakuan pagi hari"],
        medicineInfo: "Obat antiinflamasi seperti ibuprofen dan imunosupresan seperti methotrexate.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Psoriasis",
        description: "Psoriasis adalah penyakit kulit yang menyebabkan ruam merah dan bersisik.",
        symptoms: ["ruam kulit", "kulit kering", "gatal", "nyeri"],
        severity: "Ringan hingga Serius",
        emergencyTreatment: "Gunakan krim kortikosteroid dan konsultasikan dengan dokter untuk terapi lebih lanjut.",
        treatmentMethod: "Krim kortikosteroid dan terapi cahaya.",
        specialist: "Dokter Spesialis Kulit",
        source: "https://www.klikdokter.com/penyakit/psoriasis",
        features: ["Ruam merah dan bersisik", "Kulit kering dan gatal"],
        medicineInfo: "Krim kortikosteroid seperti clobetasol dan terapi cahaya.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Multiple Sklerosis",
        description: "Multiple sklerosis adalah penyakit autoimun yang menyerang sistem saraf pusat.",
        symptoms: ["kelemahan otot", "kesulitan koordinasi", "gangguan penglihatan", "kesemutan"],
        severity: "Serius",
        emergencyTreatment: "Konsultasikan dengan dokter untuk pengelolaan jangka panjang dan terapi imunomodulator.",
        treatmentMethod: "Obat imunomodulator dan terapi fisik.",
        specialist: "Dokter Spesialis Saraf",
        source: "https://www.halodoc.com/multiple-sklerosis",
        features: ["Kelemahan otot yang progresif", "Gangguan penglihatan"],
        medicineInfo: "Obat imunomodulator seperti interferon beta dan terapi fisik.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    },
    {
        name: "Anemia",
        description: "Anemia adalah kondisi di mana jumlah sel darah merah dalam darah terlalu rendah.",
        symptoms: ["kelelahan", "pucat", "sesak napas", "pusing"],
        severity: "Ringan hingga Serius",
        emergencyTreatment: "Konsumsi suplemen zat besi dan konsultasikan dengan dokter untuk penyebab mendasar.",
        treatmentMethod: "Suplemen zat besi dan pengobatan untuk penyebab yang mendasarinya.",
        specialist: "Dokter Spesialis Penyakit Dalam",
        source: "https://www.halodoc.com/anemia",
        features: ["Kelelahan dan pucat", "Sesak napas"],
        medicineInfo: "Suplemen zat besi dan obat sesuai penyebab anemia.",
        warning: "Informasi ini hanya untuk referensi. Untuk diagnosis dan pengobatan yang akurat, kunjungi dokter atau apotek."
    }
];



///sumber
document.getElementById('diseaseCount').textContent = diseases.length;

const sources = [
    "Kementerian Kesehatan RI",
    "Ikatan Dokter Indonesia",
    "Perhimpunan Dokter Spesialis",
    "WebMD Indonesia",
    "Alodokter"
];

document.getElementById('sources').textContent = sources.join(', ');
